import initScrollSuave from './modules/scroll-suave.js';
import initScrollSite from './modules/scroll-animacao.js';
import initAccordion from './modules/accordion-list.js';
import initTab from './modules/tab-nav.js';
import initModal from './modules/modal.js';
import initTooltip from './modules/tooltip.js';
import initDropdownMenu from './modules/dropdown-menu.js';
import initMenuMobile from './modules/menu-mobile.js';
import initAnimaNUmeros from './modules/anima-numeros.js';
import initFuncionamento from './modules/funcionamento.js';

initMenuMobile();
initScrollSuave();
initScrollSite();
initAccordion();
initTab();
initModal();
initTooltip();
initDropdownMenu();
initAnimaNUmeros();
initFuncionamento();